-- Application role: non-superuser, NOBYPASSRLS for tenant isolation enforcement (ADR-01)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vinea_app') THEN
        CREATE ROLE vinea_app WITH LOGIN PASSWORD 'vinea_app' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO vinea_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO vinea_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO vinea_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO vinea_app;

ALTER DEFAULT PRIVILEGES FOR ROLE vinea IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vinea_app;
ALTER DEFAULT PRIVILEGES FOR ROLE vinea IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO vinea_app;
ALTER DEFAULT PRIVILEGES FOR ROLE vinea IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO vinea_app;
