"""Add GL module tables

Revision ID: 5e9d16cd8ecc
Revises: 2f0af18ea7cd
Create Date: 2025-06-01 18:42:45.052608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9d16cd8ecc'
down_revision: Union[str, None] = '2f0af18ea7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
